# Generated by Django 4.2.1 on 2023-06-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('idtask', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdate', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, default=None, null=True)),
                ('do', models.BooleanField(default=False)),
            ],
        ),
    ]
